spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:hotel_db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  application:
    name: hotel_project
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    jdbc:
      dialect: h2
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
eureka:
  client:
    enabled: false
